### ISSUE TITLE
SPI bus speed and 16bit support

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#491]
Determine if 16bit is needed or not. Either fully support or remove option from libs.

Determine what is the transfer speed by shrinking the idle time between transactions.

**Comment by ghost** [comment]
16bit transfers may be needed/useful for SPI displays or memory chips (e.g. Flash memory).
This is faster than 8bit by design as the amount of data to transfer grows.

I see that similar to a copy of many small files versus two or three big files totalizing the same amount of data. You see what I mean ?

And this is quite easily supported in the hardware.

**Comment by Palomino34** [comment]
we do 16 bit/ 32 bit auto internally.
